In [1]:
import numpy as np

In [17]:
## Matrix operations

In [2]:
p = np.array([[1,7],[2,1],[3,2]])

In [3]:
q = np.array([[2,3],[5,7],[2,2]])

In [4]:
## Addition

In [5]:
np.add(p,q)

array([[ 3, 10],
       [ 7,  8],
       [ 5,  4]])

In [6]:
## Subtraction

In [7]:
np.subtract(p,q)

array([[-1,  4],
       [-3, -6],
       [ 1,  0]])

In [8]:
## dot product

In [9]:
r = np.array([[1,1,1],[-1,4,-6]])

In [10]:
x = np.dot(p,r)
x

array([[ -6,  29, -41],
       [  1,   6,  -4],
       [  1,  11,  -9]])

In [11]:
### Determinant of x

In [12]:
determinant_x = np.linalg.det(x)

determinant_x

-1.687538997430241e-13

In [14]:
## Matrix Inverse

In [15]:
M = np.array([[1,-1],[2,3]])

In [16]:
M_inverse = np.linalg.inv(M)
M_inverse

array([[ 0.6,  0.2],
       [-0.4,  0.2]])