# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print("NumPy version:\n", np.__version__)
print("\nNumPy configuration:\n", np.show_config())

NumPy version:
 1.23.5
blas_info:
    libraries = ['cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['/opt/conda/lib']
    include_dirs = ['/opt/conda/include']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    libraries = ['cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['/opt/conda/lib']
    include_dirs = ['/opt/conda/include']
    language = c
lapack_info:
    libraries = ['lapack', 'blas', 'lapack', 'blas']
    library_dirs = ['/opt/conda/lib']
    language = f77
lapack_opt_info:
    libraries = ['lapack', 'blas', 'lapack', 'blas', 'cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['/opt/conda/lib']
    language = c
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/conda/include']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE41,POPCNT,SSE42,AVX,F16C,FMA3,AVX2
    not found = AVX512F,

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
np.zeros(10,dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### 4. How to find the memory size of any array (★☆☆)

In [4]:
arr =np.zeros(10,dtype = int)
print('memory size: ',arr.nbytes,' bytes')

memory size:  80  bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [5]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
arr = np.zeros(10)
arr[4] = 1
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [11]:
arr = np.linspace(10,49,40, dtype = int)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [16]:
arr = np.arange(8).reshape(4,2)
arr[::-1,::-1]

array([[7, 6],
       [5, 4],
       [3, 2],
       [1, 0]])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [17]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [20]:
help(np.nonzero)

Help on function nonzero in module numpy:

nonzero(a)
    Return the indices of the elements that are non-zero.
    
    Returns a tuple of arrays, one for each dimension of `a`,
    containing the indices of the non-zero elements in that
    dimension. The values in `a` are always tested and returned in
    row-major, C-style order.
    
    To group the indices by element, rather than dimension, use `argwhere`,
    which returns a row for each non-zero element.
    
    .. note::
    
       When called on a zero-d array or scalar, ``nonzero(a)`` is treated
       as ``nonzero(atleast_1d(a))``.
    
       .. deprecated:: 1.17.0
    
          Use `atleast_1d` explicitly if this behavior is deliberate.
    
    Parameters
    ----------
    a : array_like
        Input array.
    
    Returns
    -------
    tuple_of_arrays : tuple
        Indices of elements that are non-zero.
    
    See Also
    --------
    flatnonzero :
        Return indices that are non-zero in the flattened 

In [27]:
arr = np.array([1,2,0,0,4,0])

tup = np.nonzero(arr)

tup[0]

array([0, 1, 4])

#### 11. Create a 3x3 identity matrix (★☆☆)

In [31]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [41]:
np.random.random(27).reshape(3,3,3)*100

array([[[49.89693043, 58.72079624, 57.20020565],
        [ 5.92856091, 27.25499508, 87.7203757 ],
        [ 9.19633694, 84.88240018, 35.38460142]],

       [[40.17469056, 19.68030307, 49.87619472],
        [49.14517118, 47.92925273, 72.44051998],
        [21.99074215, 46.00579361, 55.87895146]],

       [[84.60309322, 44.97287464, 93.69086952],
        [17.3339273 , 35.05563786, 54.89827084],
        [74.26679489, 12.45123115, 84.41196574]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [44]:
arr = np.random.random(100).reshape(10,10)


max_val = np.max(arr)
min_val = np.min(arr)

print(arr)
print('minimum value: ',max_val)
print('maximum value: ',min_val)

[[0.97569556 0.50949493 0.54206628 0.82769555 0.47952108 0.31805839
  0.67544113 0.71704378 0.51963087 0.34539075]
 [0.28116262 0.19314597 0.66171628 0.69799528 0.68664285 0.38526956
  0.05942189 0.89465958 0.11664883 0.43973111]
 [0.56667231 0.88615918 0.05700482 0.2113356  0.69608108 0.3724513
  0.36868991 0.29572017 0.11682384 0.98889963]
 [0.82668163 0.06513361 0.30486705 0.29590011 0.67336303 0.63892965
  0.50358297 0.73472346 0.02696506 0.75991142]
 [0.6366919  0.42462147 0.29380844 0.53867678 0.15144579 0.43988657
  0.71912563 0.87461294 0.58963257 0.63750776]
 [0.34520453 0.69607226 0.72419062 0.49091431 0.9746042  0.97352513
  0.88873058 0.8404123  0.61531535 0.03751527]
 [0.54857848 0.43218924 0.5531119  0.40726542 0.64758198 0.81156633
  0.67861886 0.81121799 0.45889458 0.47847566]
 [0.63698705 0.21289711 0.49415672 0.64111499 0.52546897 0.07870965
  0.57134942 0.23428518 0.75528507 0.9812568 ]
 [0.2586861  0.56587634 0.22818199 0.50766336 0.35420852 0.68243919
  0.98095267 

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [45]:
arr = np.random.random(30).reshape(2,15)

mean_val = np.mean(arr)

print(arr)

print('mean value: ',mean_val)

[[0.21558304 0.01264657 0.79872391 0.68185118 0.49122403 0.32755733
  0.40827294 0.36505685 0.94742738 0.84027365 0.68759523 0.26027084
  0.48010407 0.74347383 0.05871243]
 [0.75515712 0.73684382 0.94392392 0.84199969 0.35039939 0.3956215
  0.06615555 0.92913505 0.04373511 0.77590832 0.65889446 0.866601
  0.15355561 0.4314964  0.84516177]]
mean value:  0.5371120660628254


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [47]:
arr = np.ones(16).reshape(4,4)

arr[1:3,1:3] = 0


arr

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [56]:
existing_arr = np.arange(16).reshape(4,4)
zero_arr = np.zeros(36).reshape(6,6)

print('existing array:\n ',existing_arr)
print('zero array:\n ',zero_arr)

zero_arr[1:5,1:5] = existing_arr

print('array with border 0: \n',zero_arr)

existing array:
  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
zero array:
  [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  2.,  3.,  0.],
       [ 0.,  4.,  5.,  6.,  7.,  0.],
       [ 0.,  8.,  9., 10., 11.,  0.],
       [ 0., 12., 13., 14., 15.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

**0 * np.nan**  will result in nan (not a number) because any arithmetic operation involving nan will result in nan.

**np.nan == np.nan** will result in False. This is because nan is not equal to any value, including itself. To check for nan, you can use the np.isnan() function.

**np.inf > np.nan** will result in False. This is because np.inf represents positive infinity, while np.nan represents an undefined or indeterminate value. Any comparison involving np.nan will result in False.

**np.nan - np.nan** will result in nan. This is because any arithmetic operation involving nan will result in nan.

**np.nan in set([np.nan])** will result in True. Although nan is not equal to any value, including itself, it is still a member of the set containing np.nan.

**0.3 == 3 * 0.1** will result in False. This is because of a quirk in the way that floating point arithmetic is performed on computers. Due to the limitations of binary representation, the decimal number 0.1 cannot be represented exactly as a finite binary fraction. Therefore, when you perform the multiplication 3 * 0.1, the result is not exactly 0.3, but is instead a slightly different value.

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [62]:
diagonal_matrix = np.diag([1,2,3,4])
diagonal_matrix

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [65]:
diagonal_matrix = np.diag([1,2,3,4],k=-1)
diagonal_matrix

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [99]:
arr = np.zeros(64, dtype=int)

arr = arr.reshape(8,8)
arr[1::2,::2] = 1
arr[::2,1::2]=1


arr

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [100]:
import numpy as np

arr = np.zeros((6, 7, 8))

idx = np.unravel_index(99, arr.shape)

print(idx)

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [102]:
input_arr = [[0,1],[1,0]]

checkboard = np.tile(input_arr,(4,4))

checkboard

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [103]:
arr = np.arange(25).reshape(5,5)

# normalize the matrix formula
arr_norm = (arr - np.mean(arr)) / np.std(arr)

arr_norm


array([[-1.66410059, -1.52542554, -1.38675049, -1.24807544, -1.10940039],
       [-0.97072534, -0.83205029, -0.69337525, -0.5547002 , -0.41602515],
       [-0.2773501 , -0.13867505,  0.        ,  0.13867505,  0.2773501 ],
       [ 0.41602515,  0.5547002 ,  0.69337525,  0.83205029,  0.97072534],
       [ 1.10940039,  1.24807544,  1.38675049,  1.52542554,  1.66410059]])

Normalization is a common technique used in data preprocessing and machine learning to scale numerical data to a common range. The main reasons why we normalize data are:

To prevent features with large scales from dominating the learning process: When working with datasets that contain features with vastly different scales, the features with larger scales can dominate the learning process and mask the effects of the smaller-scale features. Normalizing data allows all features to contribute equally to the learning process, preventing this issue.

To improve the performance of some algorithms: Some machine learning algorithms, such as K-nearest neighbors (KNN) and support vector machines (SVM), are sensitive to the scale of the input features. Normalizing the data can improve the performance of these algorithms.

To accelerate the training process: Normalizing data can sometimes help accelerate the convergence of the training process of machine learning algorithms.

Overall, normalization is an important technique to use when working with datasets that contain features with different scales. It can help improve the performance and stability of machine learning models, and it can make the learning process more efficient.

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [104]:
import numpy as np

#  a custom data type for RGBA colors using four unsigned bytes
color_dtype = np.dtype([('R', np.uint8), ('G', np.uint8), ('B', np.uint8), ('A', np.uint8)])

#  array of colors with the custom data type
colors = np.array([(255, 0, 0, 255), (0, 255, 0, 255), (0, 0, 255, 255)], dtype=color_dtype)

print(colors)



[(255,   0,   0, 255) (  0, 255,   0, 255) (  0,   0, 255, 255)]


The purpose of creating a custom data type that represents a color as four unsigned bytes (RGBA) is to be able to efficiently store and manipulate color information in a way that is compatible with NumPy arrays and operations.

By defining a custom data type that explicitly specifies the format and size of each channel (i.e., the red, green, blue, and alpha channels of the color), we can create arrays of colors and perform element-wise operations on them using NumPy functions.

This can be useful in a wide range of applications that involve working with color data, such as image processing, computer graphics, data visualization, and machine learning. By defining a custom data type for color data, we can ensure that our code is efficient, accurate, and compatible with existing tools and libraries for working with NumPy arrays.

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [110]:
arr1 = np.arange(15).reshape(5,3)
arr2 = np.arange(6).reshape(3,2)
print('array 1: \n',arr1)
print('array 2: \n',arr2)

mat_prod = np.dot(arr1,arr2)
mat_prod

array 1: 
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
array 2: 
 [[0 1]
 [2 3]
 [4 5]]


array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [115]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])


mask = (arr > 3) & (arr < 8)
print(mask)

arr[mask] *= -1


print(arr)

[False False False  True  True  True  True False False]
[ 1  2  3 -4 -5 -6 -7  8  9]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [116]:
9
10

10

The first line of the script uses Python's built-in sum() function to sum the numbers in the range 0 to 4 (inclusive) and adds -1 to the result. The sum of the numbers in the range 0 to 4 is 10, so the output of the first line will be 9 (i.e., 10 - 1).

The second line of the script uses NumPy's sum() function to sum the numbers in the range 0 to 4 (inclusive) along the last axis (-1). Since the input is a 1D array, which has only one axis, axis=-1 is equivalent to axis=0. Therefore, the function will sum the elements along the first axis, resulting in the sum of the numbers in the range 0 to 4, which is 10. The output of the second line will be 10.

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

- Z**Z: This expression is legal and raises each element of Z to the power of itself.
- 2 << Z >> 2: This expression is legal and performs a bitwise left shift of 2 by each element of Z, followed by a bitwise right shift of the result by 2.
- Z <- Z: This expression is legal and compares each element of Z with its negation, returning a boolean array with the same shape as Z.
- 1j*Z: This expression is legal and multiplies each element of Z by 1j, the imaginary unit sqrt(-1).
- Z/1/1: This expression is legal and divides each element of Z by 1, resulting in the same array as Z.
- Z<Z>Z: This expression is not legal because it does not have a well-defined meaning in Python. It is not clear what it would mean to compare Z to itself twice using chained inequalities.

In [136]:
2**np.array([2,3])

array([4, 8])

In [137]:
z= np.array([2,3])
2 << z >> 2

array([2, 4])

In [138]:
2 <- np.array([2,3])

array([False, False])

In [139]:
1j*np.array([2,3])

array([0.+2.j, 0.+3.j])

In [140]:
np.array([2,3])/1/1

array([2., 3.])

In [142]:
2<np.array([2,3])>2

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [143]:
np.array(0) / np.array(0)

/tmp/ipykernel_123/873513115.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)


nan

In [144]:
np.array(0) // np.array(0)

/tmp/ipykernel_123/2018018105.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


0

In [145]:
np.array([np.nan]).astype(int).astype(float)

array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

In [149]:
arr = np.array([-2.3, -1.5, 0.7, 1.2, 3.8, 5.1])

rounded = np.round(arr)

rounded

array([-2., -2.,  1.,  1.,  4.,  5.])

#### 30. How to find common values between two arrays? (★☆☆)

In [152]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([3,4,5,6,7,8])

common = np.intersect1d(arr1,arr2)

common

array([3, 4, 5])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)