# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print("NumPy version:\n", np.__version__)
print("\nNumPy configuration:\n", np.show_config())

NumPy version:
 1.23.5
blas_info:
    libraries = ['cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['/opt/conda/lib']
    include_dirs = ['/opt/conda/include']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    libraries = ['cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['/opt/conda/lib']
    include_dirs = ['/opt/conda/include']
    language = c
lapack_info:
    libraries = ['lapack', 'blas', 'lapack', 'blas']
    library_dirs = ['/opt/conda/lib']
    language = f77
lapack_opt_info:
    libraries = ['lapack', 'blas', 'lapack', 'blas', 'cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['/opt/conda/lib']
    language = c
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/conda/include']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE41,POPCNT,SSE42,AVX,F16C,FMA3,AVX2
    not found = AVX512F,

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
np.zeros(10,dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### 4. How to find the memory size of any array (★☆☆)

In [4]:
arr =np.zeros(10,dtype = int)
print('memory size: ',arr.nbytes,' bytes')

memory size:  80  bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [5]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
arr = np.zeros(10)
arr[4] = 1
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [7]:
arr = np.linspace(10,49,40, dtype = int)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [8]:
arr = np.arange(8).reshape(4,2)
arr[::-1,::-1]

array([[7, 6],
       [5, 4],
       [3, 2],
       [1, 0]])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [9]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [10]:
help(np.nonzero)

Help on function nonzero in module numpy:

nonzero(a)
    Return the indices of the elements that are non-zero.
    
    Returns a tuple of arrays, one for each dimension of `a`,
    containing the indices of the non-zero elements in that
    dimension. The values in `a` are always tested and returned in
    row-major, C-style order.
    
    To group the indices by element, rather than dimension, use `argwhere`,
    which returns a row for each non-zero element.
    
    .. note::
    
       When called on a zero-d array or scalar, ``nonzero(a)`` is treated
       as ``nonzero(atleast_1d(a))``.
    
       .. deprecated:: 1.17.0
    
          Use `atleast_1d` explicitly if this behavior is deliberate.
    
    Parameters
    ----------
    a : array_like
        Input array.
    
    Returns
    -------
    tuple_of_arrays : tuple
        Indices of elements that are non-zero.
    
    See Also
    --------
    flatnonzero :
        Return indices that are non-zero in the flattened 

In [11]:
arr = np.array([1,2,0,0,4,0])

tup = np.nonzero(arr)

tup[0]

array([0, 1, 4])

#### 11. Create a 3x3 identity matrix (★☆☆)

In [12]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [13]:
np.random.random(27).reshape(3,3,3)*100

array([[[89.9125568 , 63.65641976, 76.27967451],
        [29.23888969, 67.7165172 , 72.16765037],
        [85.86886907, 17.44642913, 32.57484472]],

       [[83.56400436, 59.60460002,  7.23775799],
        [24.33579853, 22.11489029,  6.02111951],
        [76.85528877, 67.25454871, 45.53156565]],

       [[97.1591341 , 15.75298206, 25.8081216 ],
        [80.57026394, 88.9031032 , 72.24423924],
        [38.41855404, 71.11522782, 21.6161867 ]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [14]:
arr = np.random.random(100).reshape(10,10)


max_val = np.max(arr)
min_val = np.min(arr)

print(arr)
print('minimum value: ',max_val)
print('maximum value: ',min_val)

[[0.45251693 0.89990396 0.95345134 0.71490973 0.6285108  0.61769306
  0.91921687 0.58366725 0.69147895 0.62187229]
 [0.21491248 0.83609767 0.45783304 0.79613203 0.80490426 0.2026553
  0.33963502 0.99772071 0.47678265 0.81994519]
 [0.74071157 0.32360626 0.25200641 0.62204885 0.61084117 0.64052072
  0.71469749 0.52179132 0.76887436 0.650845  ]
 [0.43598634 0.42566695 0.24868625 0.36295281 0.96766813 0.29572153
  0.33630291 0.23725969 0.49460396 0.7985221 ]
 [0.65938919 0.85299808 0.82905587 0.82729653 0.94314637 0.58119748
  0.05438838 0.91027708 0.66356092 0.61766324]
 [0.09676514 0.82798229 0.95945279 0.99298089 0.39868068 0.73525937
  0.55143033 0.29195871 0.59682675 0.42031787]
 [0.72640698 0.22248166 0.26903463 0.00818525 0.70775946 0.02061599
  0.62788389 0.79224039 0.39555007 0.71182944]
 [0.58121017 0.46081493 0.3637484  0.37676566 0.83826432 0.5402982
  0.38576671 0.3466736  0.49937166 0.95457009]
 [0.89035596 0.24469827 0.10344007 0.33037965 0.08507017 0.93838174
  0.40706424 0

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [15]:
arr = np.random.random(30).reshape(2,15)

mean_val = np.mean(arr)

print(arr)

print('mean value: ',mean_val)

[[0.77209327 0.43505421 0.99785989 0.41948233 0.26040208 0.26181913
  0.78708225 0.71879278 0.43517795 0.13945191 0.87006384 0.89960603
  0.45017359 0.80132055 0.6685578 ]
 [0.89015768 0.84142047 0.36690095 0.73106364 0.56187302 0.1271705
  0.4987031  0.53797964 0.30051386 0.26999623 0.44990019 0.1610051
  0.38634951 0.76408156 0.05409469]]
mean value:  0.5286049233680481


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [16]:
arr = np.ones(16).reshape(4,4)

arr[1:3,1:3] = 0


arr

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [17]:
existing_arr = np.arange(16).reshape(4,4)
zero_arr = np.zeros(36).reshape(6,6)

print('existing array:\n ',existing_arr)
print('zero array:\n ',zero_arr)

zero_arr[1:5,1:5] = existing_arr

print('array with border 0: \n',zero_arr)

existing array:
  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
zero array:
  [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
array with border 0: 
 [[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  2.  3.  0.]
 [ 0.  4.  5.  6.  7.  0.]
 [ 0.  8.  9. 10. 11.  0.]
 [ 0. 12. 13. 14. 15.  0.]
 [ 0.  0.  0.  0.  0.  0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

**0 * np.nan**  will result in nan (not a number) because any arithmetic operation involving nan will result in nan.

**np.nan == np.nan** will result in False. This is because nan is not equal to any value, including itself. To check for nan, you can use the np.isnan() function.

**np.inf > np.nan** will result in False. This is because np.inf represents positive infinity, while np.nan represents an undefined or indeterminate value. Any comparison involving np.nan will result in False.

**np.nan - np.nan** will result in nan. This is because any arithmetic operation involving nan will result in nan.

**np.nan in set([np.nan])** will result in True. Although nan is not equal to any value, including itself, it is still a member of the set containing np.nan.

**0.3 == 3 * 0.1** will result in False. This is because of a quirk in the way that floating point arithmetic is performed on computers. Due to the limitations of binary representation, the decimal number 0.1 cannot be represented exactly as a finite binary fraction. Therefore, when you perform the multiplication 3 * 0.1, the result is not exactly 0.3, but is instead a slightly different value.

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [18]:
diagonal_matrix = np.diag([1,2,3,4])
diagonal_matrix

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [19]:
diagonal_matrix = np.diag([1,2,3,4],k=-1)
diagonal_matrix

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [20]:
arr = np.zeros(64, dtype=int)

arr = arr.reshape(8,8)
arr[1::2,::2] = 1
arr[::2,1::2]=1


arr

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [21]:
import numpy as np

arr = np.zeros((6, 7, 8))

idx = np.unravel_index(99, arr.shape)

print(idx)

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [22]:
input_arr = [[0,1],[1,0]]

checkboard = np.tile(input_arr,(4,4))

checkboard

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [23]:
arr = np.arange(25).reshape(5,5)

# normalize the matrix formula
arr_norm = (arr - np.mean(arr)) / np.std(arr)

arr_norm


array([[-1.66410059, -1.52542554, -1.38675049, -1.24807544, -1.10940039],
       [-0.97072534, -0.83205029, -0.69337525, -0.5547002 , -0.41602515],
       [-0.2773501 , -0.13867505,  0.        ,  0.13867505,  0.2773501 ],
       [ 0.41602515,  0.5547002 ,  0.69337525,  0.83205029,  0.97072534],
       [ 1.10940039,  1.24807544,  1.38675049,  1.52542554,  1.66410059]])

Normalization is a common technique used in data preprocessing and machine learning to scale numerical data to a common range. The main reasons why we normalize data are:

To prevent features with large scales from dominating the learning process: When working with datasets that contain features with vastly different scales, the features with larger scales can dominate the learning process and mask the effects of the smaller-scale features. Normalizing data allows all features to contribute equally to the learning process, preventing this issue.

To improve the performance of some algorithms: Some machine learning algorithms, such as K-nearest neighbors (KNN) and support vector machines (SVM), are sensitive to the scale of the input features. Normalizing the data can improve the performance of these algorithms.

To accelerate the training process: Normalizing data can sometimes help accelerate the convergence of the training process of machine learning algorithms.

Overall, normalization is an important technique to use when working with datasets that contain features with different scales. It can help improve the performance and stability of machine learning models, and it can make the learning process more efficient.

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [24]:
import numpy as np

#  a custom data type for RGBA colors using four unsigned bytes
color_dtype = np.dtype([('R', np.uint8), ('G', np.uint8), ('B', np.uint8), ('A', np.uint8)])

#  array of colors with the custom data type
colors = np.array([(255, 0, 0, 255), (0, 255, 0, 255), (0, 0, 255, 255)], dtype=color_dtype)

print(colors)



[(255,   0,   0, 255) (  0, 255,   0, 255) (  0,   0, 255, 255)]


The purpose of creating a custom data type that represents a color as four unsigned bytes (RGBA) is to be able to efficiently store and manipulate color information in a way that is compatible with NumPy arrays and operations.

By defining a custom data type that explicitly specifies the format and size of each channel (i.e., the red, green, blue, and alpha channels of the color), we can create arrays of colors and perform element-wise operations on them using NumPy functions.

This can be useful in a wide range of applications that involve working with color data, such as image processing, computer graphics, data visualization, and machine learning. By defining a custom data type for color data, we can ensure that our code is efficient, accurate, and compatible with existing tools and libraries for working with NumPy arrays.

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [25]:
arr1 = np.arange(15).reshape(5,3)
arr2 = np.arange(6).reshape(3,2)
print('array 1: \n',arr1)
print('array 2: \n',arr2)

mat_prod = np.dot(arr1,arr2)
mat_prod

array 1: 
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
array 2: 
 [[0 1]
 [2 3]
 [4 5]]


array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [26]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])


mask = (arr > 3) & (arr < 8)
print(mask)

arr[mask] *= -1


print(arr)

[False False False  True  True  True  True False False]
[ 1  2  3 -4 -5 -6 -7  8  9]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [27]:
9
10

10

The first line of the script uses Python's built-in sum() function to sum the numbers in the range 0 to 4 (inclusive) and adds -1 to the result. The sum of the numbers in the range 0 to 4 is 10, so the output of the first line will be 9 (i.e., 10 - 1).

The second line of the script uses NumPy's sum() function to sum the numbers in the range 0 to 4 (inclusive) along the last axis (-1). Since the input is a 1D array, which has only one axis, axis=-1 is equivalent to axis=0. Therefore, the function will sum the elements along the first axis, resulting in the sum of the numbers in the range 0 to 4, which is 10. The output of the second line will be 10.

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

- Z**Z: This expression is legal and raises each element of Z to the power of itself.
- 2 << Z >> 2: This expression is legal and performs a bitwise left shift of 2 by each element of Z, followed by a bitwise right shift of the result by 2.
- Z <- Z: This expression is legal and compares each element of Z with its negation, returning a boolean array with the same shape as Z.
- 1j*Z: This expression is legal and multiplies each element of Z by 1j, the imaginary unit sqrt(-1).
- Z/1/1: This expression is legal and divides each element of Z by 1, resulting in the same array as Z.
- Z<Z>Z: This expression is not legal because it does not have a well-defined meaning in Python. It is not clear what it would mean to compare Z to itself twice using chained inequalities.

In [28]:
2**np.array([2,3])

array([4, 8])

In [29]:
z= np.array([2,3])
2 << z >> 2

array([2, 4])

In [30]:
2 <- np.array([2,3])

array([False, False])

In [31]:
1j*np.array([2,3])

array([0.+2.j, 0.+3.j])

In [32]:
np.array([2,3])/1/1

array([2., 3.])

In [33]:
2<np.array([2,3])>2

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [40]:
np.array(0) / np.array(0)

nan

In [41]:
np.array(0) // np.array(0)

0

In [42]:
np.array([np.nan]).astype(int).astype(float)

array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

In [43]:
arr = np.array([-2.3, -1.5, 0.7, 1.2, 3.8, 5.1])

rounded = np.round(arr)

rounded

array([-2., -2.,  1.,  1.,  4.,  5.])

#### 30. How to find common values between two arrays? (★☆☆)

In [44]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([3,4,5,6,7,8])

common = np.intersect1d(arr1,arr2)

common

array([3, 4, 5])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [39]:
import warnings
warnings.filterwarnings("ignore")

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [45]:
np.sqrt(-1)

nan

In [46]:
np.emath.sqrt(-1)

1j

So they are not equal.

When np.sqrt(-1) is evaluated, it will return a runtime warning and return nan (not a number) as the result. This is because NumPy's sqrt() function does not support complex numbers, and the square root of a negative real number is a complex number.

On the other hand, np.emath.sqrt(-1) returns the expected value of 1j, which represents the square root of -1 in the complex plane. The np.emath module provides functions that support complex numbers and is the recommended way to handle complex numbers in NumPy.

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [49]:
from datetime import datetime, timedelta

today = datetime.now().date()

yesterday = today - timedelta(days=1)

tomorrow = today + timedelta(days=1)

print("Yesterday was:", yesterday)
print("Today is:", today)
print("Tomorrow will be:", tomorrow)

Yesterday was: 2023-05-08
Today is: 2023-05-09
Tomorrow will be: 2023-05-10


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [61]:
from datetime import datetime,timedelta

startDate = datetime(2016,7,1)
endDate = datetime(2016,7,31)

num_of_days = (endDate-startDate).days + 1

days_arr = np.array([startDate + timedelta(days=i) for i in range(num_of_days)])

days_arr

array([datetime.datetime(2016, 7, 1, 0, 0),
       datetime.datetime(2016, 7, 2, 0, 0),
       datetime.datetime(2016, 7, 3, 0, 0),
       datetime.datetime(2016, 7, 4, 0, 0),
       datetime.datetime(2016, 7, 5, 0, 0),
       datetime.datetime(2016, 7, 6, 0, 0),
       datetime.datetime(2016, 7, 7, 0, 0),
       datetime.datetime(2016, 7, 8, 0, 0),
       datetime.datetime(2016, 7, 9, 0, 0),
       datetime.datetime(2016, 7, 10, 0, 0),
       datetime.datetime(2016, 7, 11, 0, 0),
       datetime.datetime(2016, 7, 12, 0, 0),
       datetime.datetime(2016, 7, 13, 0, 0),
       datetime.datetime(2016, 7, 14, 0, 0),
       datetime.datetime(2016, 7, 15, 0, 0),
       datetime.datetime(2016, 7, 16, 0, 0),
       datetime.datetime(2016, 7, 17, 0, 0),
       datetime.datetime(2016, 7, 18, 0, 0),
       datetime.datetime(2016, 7, 19, 0, 0),
       datetime.datetime(2016, 7, 20, 0, 0),
       datetime.datetime(2016, 7, 21, 0, 0),
       datetime.datetime(2016, 7, 22, 0, 0),
       datetime.dat

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [73]:
A = np.array([1, 2, 3], dtype= int)
B = np.array([4, 5, 6], dtype = int)


A //=2
print(A)

A*=-1
print(A)

A *= B + A

print(A)

[0 1 1]
[ 0 -1 -1]
[ 0 -4 -5]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [83]:
# floor method

arr = np.random.random(10) * 10

int_part = np.floor(arr)

In [84]:
# astype method

int_part = arr.astype(int)

int_part

array([3, 1, 9, 8, 7, 7, 6, 1, 8, 6])

In [86]:
# trunc method

int_part = np.trunc(arr)

int_part


array([3., 1., 9., 8., 7., 7., 6., 1., 8., 6.])

In [87]:
# using list

int_part = [int(i) for i in arr]

int_part

[3, 1, 9, 8, 7, 7, 6, 1, 8, 6]

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [94]:
arr = np.tile(np.arange(6),(5,1))

arr

array([[0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [96]:
def generate_int():
    for i in range(10):
        yield np.random.randint(100)
        
arr = np.fromiter(generate_int(),dtype = int)

arr

array([91, 76, 86, 25, 59, 58, 98, 76,  6, 76])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [109]:
vector = np.linspace(0,1,12)[1:-1]

vector

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [114]:
vec = np.random.rand(10)

vec = np.sort(vec)

vec

array([0.00817359, 0.07522346, 0.11307206, 0.14988805, 0.23458005,
       0.50080495, 0.54067722, 0.60041173, 0.62971995, 0.77764328])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [115]:
arr = np.array([4,7,2,5,8,3])

total = sum(arr)

total

29

In terms of small numbers of array sum() is faster than np.sum() but for larger array elements np.sum() is more faster.

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [121]:
A = np.random.rand(10)
B = np.random.rand(10)
C = np.array([4,7,2,5,8,3])
D = np.array([4,7,2,5,8,3])

if np.array_equal(A,B):
    print('A and B are equal')
    
if np.array_equal(C,D):
    print('C and D are equal')

C and D are equal


#### 43. Make an array immutable (read-only) (★★☆)

In [122]:

A = np.array([1, 2, 3, 4, 5])

A.flags.writeable = False

A[0] = 10


ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [123]:
# Create a random 10x2 matrix representing cartesian coordinates
cartesian = np.random.rand(10, 2)

# Convert cartesian coordinates to polar coordinates
distance = np.hypot(cartesian[:, 0], cartesian[:, 1])
angle = np.arctan2(cartesian[:, 1], cartesian[:, 0])

# Create a 10x2 matrix representing polar coordinates
polar = np.column_stack((distance, angle))

print("Cartesian coordinates:")
print(cartesian)
print("Polar coordinates:")
print(polar)

Cartesian coordinates:
[[0.2309582  0.39598814]
 [0.67623022 0.18368822]
 [0.4360329  0.87875454]
 [0.46075123 0.76353481]
 [0.23491854 0.25586493]
 [0.94147028 0.95865832]
 [0.25076238 0.19369875]
 [0.31134535 0.57687846]
 [0.1360486  0.22087308]
 [0.60230105 0.97806718]]
Polar coordinates:
[[0.45841935 1.0427876 ]
 [0.70073438 0.26523569]
 [0.98098635 1.110198  ]
 [0.8917831  1.02784762]
 [0.34735224 0.82805177]
 [1.34364878 0.79444364]
 [0.31686114 0.65770835]
 [0.65553389 1.07588993]
 [0.25941114 1.01872536]
 [1.14864353 1.01883471]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [133]:
arr = np.round(np.random.rand(10) * 100).astype(int)

max_index = np.argmax(arr)
print(arr[max_index])
arr[max_index] = 0

arr

99


array([36, 12, 61, 55, 51, 72, 25, 81,  0, 47])

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [134]:
# Define the number of points along each axis
n = 5

# Generate a grid of x and y coordinates
x, y = np.meshgrid(np.linspace(0, 1, n), np.linspace(0, 1, n))

# Stack the x and y coordinates into a structured array
coords = np.column_stack((x.ravel(), y.ravel()))

print(coords)

[[0.   0.  ]
 [0.25 0.  ]
 [0.5  0.  ]
 [0.75 0.  ]
 [1.   0.  ]
 [0.   0.25]
 [0.25 0.25]
 [0.5  0.25]
 [0.75 0.25]
 [1.   0.25]
 [0.   0.5 ]
 [0.25 0.5 ]
 [0.5  0.5 ]
 [0.75 0.5 ]
 [1.   0.5 ]
 [0.   0.75]
 [0.25 0.75]
 [0.5  0.75]
 [0.75 0.75]
 [1.   0.75]
 [0.   1.  ]
 [0.25 1.  ]
 [0.5  1.  ]
 [0.75 1.  ]
 [1.   1.  ]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [135]:

# Define input arrays X and Y
X = np.array([1, 2, 3, 4])
Y = np.array([5, 6, 7])

# Construct the Cauchy matrix C
C = 1.0 / (X[:, None] - Y)

print(C)

[[-0.25       -0.2        -0.16666667]
 [-0.33333333 -0.25       -0.2       ]
 [-0.5        -0.33333333 -0.25      ]
 [-1.         -0.5        -0.33333333]]


In linear algebra, a Cauchy matrix is a matrix with entries defined as:

C_ij = 1 / (x_i - y_j)

where x and y are two vectors of distinct non-zero real numbers.

The Cauchy matrix is named after the French mathematician Augustin Louis Cauchy. It arises in various applications, including interpolation problems, numerical integration, and signal processing.

One important property of the Cauchy matrix is that it is singular, meaning that its determinant is zero. This implies that the matrix is not invertible, and that its null space is non-trivial.

The singularity of the Cauchy matrix also implies that it is ill-conditioned, meaning that small changes to the entries of the matrix can cause large changes in its solution. This can make it challenging to compute solutions to problems involving the Cauchy matrix.

Despite these challenges, the Cauchy matrix has important applications in a variety of fields, including physics, engineering, and finance.

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [137]:
import numpy as np

dtypes = [np.int8, np.int16, np.int32, np.int64, np.uint8, np.uint16, np.uint32, np.uint64,
          np.float16, np.float32, np.float64, np.complex64, np.complex128]

for dtype in dtypes:
    if np.issubdtype(dtype, np.integer):
        info = np.iinfo(dtype)
        print(f"{dtype}: {info.min}, {info.max}")
    elif np.issubdtype(dtype, np.floating):
        info = np.finfo(dtype)
        print(f"{dtype}: {info.min}, {info.max}")
    elif dtype == np.bool_:
        print(f"{dtype}: {False}, {True}")
    else:
        print(f"{dtype}: not inexact")


<class 'numpy.int8'>: -128, 127
<class 'numpy.int16'>: -32768, 32767
<class 'numpy.int32'>: -2147483648, 2147483647
<class 'numpy.int64'>: -9223372036854775808, 9223372036854775807
<class 'numpy.uint8'>: 0, 255
<class 'numpy.uint16'>: 0, 65535
<class 'numpy.uint32'>: 0, 4294967295
<class 'numpy.uint64'>: 0, 18446744073709551615
<class 'numpy.float16'>: -65504.0, 65504.0
<class 'numpy.float32'>: -3.4028234663852886e+38, 3.4028234663852886e+38
<class 'numpy.float64'>: -1.7976931348623157e+308, 1.7976931348623157e+308
<class 'numpy.complex64'>: not inexact
<class 'numpy.complex128'>: not inexact


#### 49. How to print all the values of an array? (★★☆)

In [138]:
# Create a 1D array with 10 elements
arr = np.arange(10)

# Print the entire array
np.set_printoptions(threshold=np.inf)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


To print all the values of an array in NumPy, you can simply use the print() function to print the array object. By default, NumPy will print the entire array if it is small enough to fit on the screen. However, if the array is too large, NumPy will only print the beginning and end of the array. To override this behavior and force NumPy to print the entire array, you can use the set_printoptions() function from the numpy module

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [139]:

# Example vector
vec = np.array([1.2, 3.4, 5.6, 7.8, 9.0])

# Scalar to find the closest value to
scalar = 4.5

# Compute the absolute difference between each element and the scalar
diff = np.abs(vec - scalar)

# Find the index of the closest value
index = np.argmin(diff)

# Get the closest value
closest_value = vec[index]

print(closest_value)

5.6


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [140]:

# Define the data type of the structured array
dt = np.dtype([('position', [('x', float), ('y', float)]), ('color', [('r', float), ('g', float), ('b', float)])])

# Create a structured array
arr = np.array([((1.0, 2.0), (255.0, 0.0, 0.0)), ((3.0, 4.0), (0.0, 255.0, 0.0))], dtype=dt)

# Print the structured array
print(arr)

[((1., 2.), (255.,   0., 0.)) ((3., 4.), (  0., 255., 0.))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [142]:
from scipy.spatial.distance import pdist

# Generate a random vector with shape (100, 2)
random_vector = np.random.rand(100, 2)

# Compute pairwise distances between points
distances = pdist(random_vector)

# Print the distances
#print(distances)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [145]:
a = np.array([1.1, 2.2, 3.3, 4.4], dtype=np.float32)

# convert to an integer array in place
a = a.astype(np.int32)
a

array([1, 2, 3, 4], dtype=int32)

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [147]:
# Read the file using genfromtxt
arr = np.genfromtxt('file.txt', delimiter=',', dtype=np.float64, missing_values='', filling_values=np.nan)

# Print the resulting array
print(arr)

[[ 1.  2.  3.  4.  5.]
 [ 6. nan nan  7.  8.]
 [nan nan  9. 10. 11.]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [148]:

arr = np.array([[1, 2], [3, 4]])

for index, value in np.ndenumerate(arr):
    print(index, value)

(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [149]:

def gaussian_array(size, center, sigma):
    x, y = np.meshgrid(np.arange(size[0]), np.arange(size[1]))
    x = x - center[0]
    y = y - center[1]
    dist = np.sqrt(x**2 + y**2)
    gaussian = np.exp(-dist**2 / (2 * sigma**2))
    return gaussian

gaussian = gaussian_array((5, 5), (2, 2), 1.0)
print(gaussian)

[[0.01831564 0.082085   0.13533528 0.082085   0.01831564]
 [0.082085   0.36787944 0.60653066 0.36787944 0.082085  ]
 [0.13533528 0.60653066 1.         0.60653066 0.13533528]
 [0.082085   0.36787944 0.60653066 0.36787944 0.082085  ]
 [0.01831564 0.082085   0.13533528 0.082085   0.01831564]]


#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [150]:
arr = np.zeros((5, 5))

# Number of elements to randomly place
p = 3

# Generate a random list of unique indices to place the elements
indices = np.random.choice(range(5*5), p, replace=False)

# Set the values of the selected indices to 1
arr.flat[indices] = 1

# Print the resulting array
print(arr)

[[0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [151]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Compute row-wise means
row_means = np.mean(A, axis=1)

# Subtract row-wise means from A
A_sub_mean = A - row_means[:, np.newaxis]

print(A_sub_mean)

[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


#### 59. How to sort an array by the nth column? (★★☆)

In [152]:
arr = np.random.randint(0, 10, size=(5, 3))
print("Original array:\n", arr)

# sort the array by the 2nd column (index 1)
n = 1
indices = arr[:, n].argsort()
arr_sorted = arr[indices]

print(f"\nSorted by {n}th column:\n", arr_sorted)

Original array:
 [[7 7 9]
 [1 7 2]
 [1 6 9]
 [1 9 3]
 [0 9 2]]

Sorted by 1th column:
 [[1 6 9]
 [7 7 9]
 [1 7 2]
 [1 9 3]
 [0 9 2]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [156]:
arr1 = np.array([[1, 0, 0], [4, 0, 6], [0, 0, 0]])


arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# check if arr1 has null columns
null_columns1 = np.all(arr1 == 0, axis=0)

# check if arr2 has null columns
null_columns2 = np.all(arr2 == 0, axis=0)

print(null_columns1) 
print(null_columns2)  

[False  True False]
[False False False]


#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)