###`Q-1:` Create a random 3x4 matrix with value between 0-100. And perform below tasks

    i. Sort this matrix. np.sort()
    ii. Sort this matrix based on values in 2nd column.
    iii. Sort this matrix based on max value in each row.
    iv. Sort based on elements value.


See examples:
```
arr = 
    [[92 90 74]
    [ 6 63 93]
    [15 93 96]
    [70 60 48]]
```
```
i. np.sort
[[74 90 92]
 [ 6 63 93]
 [15 93 96]
 [48 60 70]]

ii. based on 2nd column
[[70 60 48]
 [ 6 63 93]
 [92 90 74]
 [15 93 96]]

iii. based on row max- ascending
[[15 93 96]
 [ 6 63 93]
 [92 90 74]
 [70 60 48]]

iv. based on elements value
[[ 6 15 48]
 [60 63 70]
 [74 90 92]
 [93 93 96]]

```

In [85]:
# code here
import numpy as np
arr = np.array([[92, 90, 74],
    [ 6, 63, 93],
    [15, 93, 96],
    [70, 60, 48]])

arr = np.sort(arr)
arr


array([[74, 90, 92],
       [ 6, 63, 93],
       [15, 93, 96],
       [48, 60, 70]])

In [86]:
# based on 2nd column
arr[arr[:,1].argsort()]

array([[48, 60, 70],
       [ 6, 63, 93],
       [74, 90, 92],
       [15, 93, 96]])

**argsort()** is a useful NumPy method for obtaining the indices that would sort an array in ascending order. It is particularly useful for sorting along a specific axis of a multi-dimensional array.

[[15 93 96]
 [ 6 63 93]
 [92 90 74]
 [70 60 48]]

In [87]:

sorted_arr = arr[arr.max(axis=1).argsort()][::-1]


print(sorted_arr)


[[15 93 96]
 [ 6 63 93]
 [74 90 92]
 [48 60 70]]


In [88]:
# based on element value

np.sort(arr, axis=None).reshape(4,3)


array([[ 6, 15, 48],
       [60, 63, 70],
       [74, 90, 92],
       [93, 93, 96]])

###`Q-2:` There is an array of marks of 5 students in 4 subjects. Further you are asked to perform below task.
    i. Add marks every student of an extra subject in the same array.
    ii. Add two new students marks in respective 5 subjects.(one subject added in above task)
    iii. Add extra column with sum of all subjects(5-subjects) marks
    iv. Sort the array(non-ascending order) on total marks column--one added in above task. Show top 2 rows.

Note: Change dimension of arrays during concatenation or appending if required.

Given Array-
```
marks = [[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]]

extra_subject = [41, 87, 72, 36, 92]
#Two extra students record-
rec1 = [77, 83, 98, 95, 89]
rec2 = [92, 71, 52, 61, 53]
```

In [183]:
#
marks = np.array([[13, 10, 9, 33],
                  [63, 46, 90, 42],
                  [39, 76, 13, 29],
                  [82, 9, 29, 78],
                  [67, 61, 59, 36]])

extra_subject = np.array([41,87,72,36,92])

print(marks.shape,extra_subject.shape)

new_extra_subject = extra_subject[:,np.newaxis]



marks = np.concatenate((marks,new_extra_subject),axis=1)
marks

(5, 4) (5,)


array([[13, 10,  9, 33, 41],
       [63, 46, 90, 42, 87],
       [39, 76, 13, 29, 72],
       [82,  9, 29, 78, 36],
       [67, 61, 59, 36, 92]])

In [184]:
# ii
rec1 = [77, 83, 98, 95, 89]
rec2 = [92, 71, 52, 61, 53]
new_marks = np.array([rec1,rec2])

print(new_marks.shape)

new_marks = new_marks.reshape(-2,2)
print(new_marks.shape)

marks = np.append(marks,new_marks).reshape(7,5)
marks

(2, 5)
(5, 2)


array([[13, 10,  9, 33, 41],
       [63, 46, 90, 42, 87],
       [39, 76, 13, 29, 72],
       [82,  9, 29, 78, 36],
       [67, 61, 59, 36, 92],
       [77, 83, 98, 95, 89],
       [92, 71, 52, 61, 53]])

In [185]:
# iii

sum_col = np.sum(marks,axis=1)
print(sum_col.shape)
new_sum_col = sum_col[:,np.newaxis]
new_sum_col

(7,)


array([[106],
       [328],
       [229],
       [234],
       [315],
       [442],
       [329]])

In [186]:
marks = np.concatenate((marks,new_sum_col),axis=1)
marks

array([[ 13,  10,   9,  33,  41, 106],
       [ 63,  46,  90,  42,  87, 328],
       [ 39,  76,  13,  29,  72, 229],
       [ 82,   9,  29,  78,  36, 234],
       [ 67,  61,  59,  36,  92, 315],
       [ 77,  83,  98,  95,  89, 442],
       [ 92,  71,  52,  61,  53, 329]])

In [198]:
# iv
indices = np.argsort(marks[:,-1])[::-1]

print(indices)

result = marks[indices]
print(result)
print('only two row: \n',result[0:2,:])

[5 6 1 4 3 2 0]
[[ 77  83  98  95  89 442]
 [ 92  71  52  61  53 329]
 [ 63  46  90  42  87 328]
 [ 67  61  59  36  92 315]
 [ 82   9  29  78  36 234]
 [ 39  76  13  29  72 229]
 [ 13  10   9  33  41 106]]
only two row: 
 [[ 77  83  98  95  89 442]
 [ 92  71  52  61  53 329]]


###`Q-3:` Find unique arrays from a 2D array column wise and row wise.
```
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
```
Expected Result-
```
Row Wise
[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]

Col Wise
[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]
```

In [199]:
# row wise
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])


np.unique(arr,axis=0)


array([[0, 9, 1, 2, 8, 8],
       [1, 2, 3, 3, 1, 1],
       [1, 2, 3, 8, 8, 8]])

In [200]:
# column wise
np.unique(arr,axis=1)

array([[1, 1, 2, 3, 3],
       [0, 8, 9, 1, 2],
       [1, 8, 2, 3, 8],
       [1, 1, 2, 3, 3]])

###`Q-4:` Flip given 2-D array along both axes at the same time.

In [201]:
# code here
import numpy as np


arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])


flipped_arr = np.flip(arr, axis=(0,1))



print("Original array:\n", arr)
print("Flipped array:\n", flipped_arr)

Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Flipped array:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]


### `Q-5:` Get row numbers of NumPy array having element larger than X.
```
arr = [[1,2,3,4,5], 
      [10,-3,30,4,5], 
      [3,2,5,-4,5], 
      [9,7,3,6,5]] 

X = 6
```

In [204]:
# row numbers
arr = np.array([[1,2,3,4,5], 
      [10,-3,30,4,5], 
      [3,2,5,-4,5], 
      [9,7,3,6,5]])

x=6

np.where(arr>x)[0]

array([1, 1, 3, 3])

That means in row number 2 there are two elements greater than 6, that is why it is showing 1,1

then in row number 4 there are two elements greater than 6, that's why showing 3,3

In [205]:
# Column numbers
arr = np.array([[1,2,3,4,5], 
      [10,-3,30,4,5], 
      [3,2,5,-4,5], 
      [9,7,3,6,5]])

x=6

np.where(arr>x)[1]

array([0, 2, 0, 1])

### `Q-6:` How to convert an array of arrays into a flat 1d array?


In [206]:
# These arrays are given.
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

In [210]:
# code here
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
flat_arr = arr.flatten()

print(flat_arr) 

[1 2 3 4 5 6 7 8 9]


### `Q-7:` You are given a array. You have to find the minimum and maximum array element and remove that from the array.

```python
import numpy as np

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
```

In [215]:
# code here

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))

max_ele = np.max(arr)
min_ele = np.min(arr)
print('max_element',max_ele)
print('min_element',min_ele)

max_ele_index = np.argmax(arr)
min_ele_index = np.argmin(arr)
arr = np.delete(arr,[min_ele_index,max_ele_index])

max_ele = np.max(arr)
min_ele = np.min(arr)
print('max_element',max_ele)
print('min_element',min_ele)

max_element 998
min_element 103
max_element 997
min_element 117


### `Q-8:` You are given an arrays. You have to limit this array's elements between 100 to 200. $arr ∈ [100, 700]$. So replace those values accordingly with the minimum and maximum value. Then sort the array and perform the cumulative sum of that array.

In [234]:
# code here
arr = np.random.randint(100,700,100)
arr = np.clip(arr,100,200)
arr = np.sort(arr)
cumulative_sum = np.cumsum(arr)

print(cumulative_sum)




[  125   279   437   600   767   936  1105  1275  1447  1630  1819  2019
  2219  2419  2619  2819  3019  3219  3419  3619  3819  4019  4219  4419
  4619  4819  5019  5219  5419  5619  5819  6019  6219  6419  6619  6819
  7019  7219  7419  7619  7819  8019  8219  8419  8619  8819  9019  9219
  9419  9619  9819 10019 10219 10419 10619 10819 11019 11219 11419 11619
 11819 12019 12219 12419 12619 12819 13019 13219 13419 13619 13819 14019
 14219 14419 14619 14819 15019 15219 15419 15619 15819 16019 16219 16419
 16619 16819 17019 17219 17419 17619 17819 18019 18219 18419 18619 18819
 19019 19219 19419 19619]


### `Q-9:` You are given a array ($arr ∈ [0, 1]$). First you have round off the elements upto 3 decimal places and compare that
- 0th percentile == minimum value of the array
- 100th percentile == maximum value of the array
- also find the difference betwen 51th percenile and 50th percentile values

In [235]:
# code here
arr = np.array([0.123456, 0.56789, 0.987654, 0.345678, 0.654321, 0.987654])
arr = np.round(arr, decimals=3)


min_val = np.percentile(arr, 0)
max_val = np.percentile(arr, 100)


p50 = np.percentile(arr, 50)
p51 = np.percentile(arr, 51)


diff = p51 - p50

# Print the results
print("Array after rounding off:", arr)
print("Minimum value:", min_val)
print("Maximum value:", max_val)
print("Difference between 51th and 50th percentiles:", diff)

Array after rounding off: [0.123 0.568 0.988 0.346 0.654 0.988]
Minimum value: 0.123
Maximum value: 0.988
Difference between 51th and 50th percentiles: 0.0042999999999999705


np.percentile is a NumPy function that calculates the value at a specific percentile of a given array. Percentiles are a way to divide a dataset into equal parts. For example, the median is the 50th percentile because it divides the dataset into two equal parts.

The np.percentile function takes three arguments:

a: the input array
q: the percentile(s) to calculate, can be a single value or a sequence of values
axis: the axis or axes along which to perform the calculation, optional
The function returns the percentile value(s) as a float or an array of floats. By default, the function uses linear interpolation to estimate the percentile values, but this can be changed using the interpolation argument.

In summary, np.percentile is a useful function for calculating percentiles of a dataset, which can provide valuable information about the distribution of the data.

Imagine you have a group of 100 people and you want to see how you compare to everyone else in terms of height. The 50th percentile would be the height where half of the people are taller than you and the other half are shorter than you. If you are taller than 70 out of the 100 people, then you are in the 70th percentile.