### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences (List or sets) 

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

In [1]:
# importing numpy array
import numpy as np

In [2]:
# 1D array or vector

np.array([1,2,4])

array([1, 2, 4])

In [3]:
# 2D array or matrix

np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [4]:
# 3D array or Tensor

np.array([[[1,2],[3,4],[5,6]]])

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [5]:
# changing array data type using dtype

np.array([1,2,5],dtype=float)

array([1., 2., 5.])

In [6]:
np.array([3,4,6],dtype=complex)

array([3.+0.j, 4.+0.j, 6.+0.j])

In [7]:
np.array([4,2,6],dtype=bool) # every number is true except 0

array([ True,  True,  True])

In [8]:
# np.arange

In [9]:
np.arange(22,33)

array([22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32])

In [10]:
np.arange(22,34,2)

array([22, 24, 26, 28, 30, 32])

In [11]:
# reshape array with matrix

In [12]:
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [13]:
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

##### The number of products in reshape function after multiplication should be equal to number of items in the array

# np ones and np zeros and np random
Basically they are used for initialization

In [14]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.random.random((3,4))*100  # this will give me 0-100 random values.

array([[ 9.90440671, 66.69651161, 23.58375297, 22.03741768],
       [78.39583811, 90.08032184, 75.49778438, 24.89177599],
       [ 8.05668993, 13.7683625 , 72.06263971, 18.0492561 ]])

In [17]:
# np linspace (Linearly spaced)

np.linspace(lowerbound,upperbound,how_many_elements_you_want)

In [18]:
np.linspace(-10,10,11)

array([-10.,  -8.,  -6.,  -4.,  -2.,   0.,   2.,   4.,   6.,   8.,  10.])

The linspace function takes three arguments:

- start: The starting value of the sequence
- stop: The ending value of the sequence
- num: The number of evenly spaced values to generate between start and stop (every element takes equal distances)
- It will keep starting and ending number in the array

In [19]:
# np identity 

np.identity() An identity matrix is a special type of matrix that has ones along the diagonal and zeros everywhere else. It is denoted by the symbol "I", and is also known as a unit matrix or a diagonal matrix. The diagonal elements of an identity matrix are always equal to 1, while all other elements are equal to 0.

In [20]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Array attributes

In [21]:
a0 = np.arange(11,dtype=np.int32)
a0

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int32)

In [22]:
a = np.arange(11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
b= np.arange(8).reshape(2,4)
b

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [24]:
c = np.arange(8).reshape(2,2,2)
c

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [25]:
# ndim attribute (it prints how many dimensions your array has)

In [26]:
a.ndim

1

In [27]:
b.ndim

2

In [28]:
c.ndim

3

In [29]:
# shape attribute

In [30]:
print(a.shape)

(11,)


means it is a 1D array which has 11 elements

In [31]:
print(b.shape)

(2, 4)


means it is a 2D array which has 2 rows and four columns and 2*4 = 8 elements

In [32]:
print(c.shape)

(2, 2, 2)


means it is a 3D array which has 2 arrays of (2 rows and 2 columns) and 2 * 2 * 2 = 8 elements

In [33]:
# Size attribute

In [34]:
a0.size

11

In [35]:
a.size

11

In [36]:
b.size

8

In [37]:
c.size

8

In [38]:
# item size attribute

In [39]:
a0.itemsize

4

In [40]:
a.itemsize

8

In [41]:
b.itemsize

8

In [42]:
c.itemsize

8

#### size vs itemsize

size is the total number of elements in a DataFrame or Series object, calculated by multiplying the number of rows by the number of columns. It gives the total size of the object in terms of the number of elements it contains.

itemsize is the size of each element in the DataFrame or Series object in bytes. It gives the memory size of each element in the object.

In [43]:
# dtype attribute (shows the type of the elements of the array)

In [44]:
a0.dtype

dtype('int32')

In [45]:
a.dtype

dtype('int64')

In [46]:
b.dtype

dtype('int64')

In [47]:
c.dtype

dtype('int64')

# Changing Data Types of an array

In [48]:
print('a before: ',a.dtype)

# will convert a array from int 64 to int 32

a = a.astype(np.int32)

print('a after: ',a.dtype)

a before:  int64
a after:  int32


In [49]:
print('a before: ',a.dtype)

a = a.astype(float)

print('a after: ',a.dtype)

a before:  int32
a after:  float64


## Scaler operations

In [51]:
a1 = np.arange(12).reshape(3,4)
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [52]:
a1+2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [54]:
a1*4

array([[ 0,  4,  8, 12],
       [16, 20, 24, 28],
       [32, 36, 40, 44]])

In [55]:
a1/4

array([[0.  , 0.25, 0.5 , 0.75],
       [1.  , 1.25, 1.5 , 1.75],
       [2.  , 2.25, 2.5 , 2.75]])

In [56]:
a1%4

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

## Relational operations

In [65]:
a1 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [66]:
a1 > 8

array([[False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True]])

In [67]:
a1 <= 8

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True, False, False, False]])

In [68]:
a1 == 10

array([[False, False, False, False],
       [False, False, False, False],
       [False, False,  True, False]])

## Vector operations

In [69]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [71]:
a2 = np.arange(12,24).reshape(3,4)
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [72]:
a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [73]:
a1 - a2

array([[-12, -12, -12, -12],
       [-12, -12, -12, -12],
       [-12, -12, -12, -12]])

In [74]:
a1 * a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [78]:
a1/a2

array([[0.        , 0.07692308, 0.14285714, 0.2       ],
       [0.25      , 0.29411765, 0.33333333, 0.36842105],
       [0.4       , 0.42857143, 0.45454545, 0.47826087]])