In [1]:
import numpy as np

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [2]:
#Code here
arr = np.zeros(10, dtype = int)

arr[4] = 1

arr

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [3]:
#Code here

a = int(input('Give input for row numbers: '))
b = int(input('Give input for column numbers: '))


arr = np.random.randint(low=0,high=100,size=a*b).reshape((a,b))

avg = np.mean(arr)

print('array: ',arr)
print('avg: ',avg)

Give input for row numbers: 5
Give input for column numbers: 4
array:  [[86 82 52 99]
 [96 13  8 15]
 [68  0 61  1]
 [69 54 65 82]
 [93 61  4 17]]
avg:  51.3



###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```

[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [4]:
#Code here
def onezero(a,b):
  if a>2 and b>2:
    arr = np.ones((a,b),dtype=int)
    arr[1:a-1,1:b-1] = 0
    return arr
  else: 
    return np.ones((a,b),dtype=int)


ans = onezero(2,2)
print(ans)

[[1 1]
 [1 1]]


###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [5]:
#Code here

np.linspace(0,1,12)[1:11]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [68]:
#Code here
#No to create a identity matrix , row and column must be same size

###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [7]:
#Code here
np.linspace(0,4,25, dtype = int).reshape(5,5)

array([[0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1],
       [1, 1, 2, 2, 2],
       [2, 2, 2, 3, 3],
       [3, 3, 3, 3, 4]])

###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3]) 
```


In [8]:
#code here
import math
point = np.array([2,3]) 
distance = []
arr = np.random.randint(low=1,high=100,size=10*2).reshape((10,2))

for i in range(len(arr)):
  #print(arr[i])
  x1 = point[0]
  y1 = point[1]
  x2 = arr[i][0]
  y2 = arr[i][1]

  d = ((x2-x1)**2 + (y2-y1)**2)**.5
  #print(d)
  distance.append(d)

print(distance)

[95.1892851112981, 72.47068372797375, 124.96399481450646, 53.150729063673246, 11.704699910719626, 66.2872536767062, 56.60388679233962, 68.73136110975832, 95.90099061010788, 76.48529270389177]


###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [9]:
#Code here

import numpy as np

arr = np.zeros((6, 7, 8))

# find the indices of the 100th element
idx = np.unravel_index(99, arr.shape)


#print(arr)
print(idx)

(1, 5, 3)


np.unravel_index() is a function in NumPy that takes a single integer index and the shape of an array, and returns the tuple of indices that corresponds to the position of the element at that index in the flattened array.

In the given example, we first create a NumPy array arr with shape (6, 7, 8) and fill it with zeros using the np.zeros() function. Then, we use np.unravel_index() to find the tuple of indices that corresponds to the 100th element in the flattened array.

The arr.shape attribute returns the shape of the arr array as a tuple. In this case, the shape tuple is (6, 7, 8), which means that arr has 6 rows, 7 columns, and 8 "depth" or "height" dimensions.

By passing the integer index 99 and the shape tuple (6, 7, 8) to np.unravel_index(), we get the tuple of indices (1, 5, 3) that corresponds to the position of the 100th element in the flattened arr array. This means that the element at position (1, 5, 3) in the original 3D array has a flattened index of 99.






### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [10]:
#Code here
arr = [1,2,3,4,-8,-10]

ans = np.array(arr[::-1], dtype=float)

ans


array([-10.,  -8.,   4.,   3.,   2.,   1.])

### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [11]:
#Code here

numpy_arr = np.arange(12).reshape((3,4))
print(numpy_arr.size)

12


### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01, 
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

The softmax function is a commonly used activation function in machine learning and deep learning. It is a mathematical function that takes as input a vector of numbers and returns a vector of the same size, with values that represent the probabilities of each input value belonging to different categories.

 Let's say we have a list of students and we want to predict their grades in a test. We have some information about each student, like how many hours they studied, how much sleep they got, and how much they enjoyed the subject. We want to use this information to predict the grade each student will get.

We can represent each student's information as a list of numbers. For example, one student's information might be [10, 7, 8], where the first number represents the hours they studied, the second number represents the hours of sleep they got, and the third number represents how much they enjoyed the subject.

We can use the softmax function to predict the grade each student will get. We'll first train our computer using data from other students. We'll have a list of each student's information and the grade they got in the test. We'll use this data to figure out the best values for the numbers we use in the softmax function.

Once we've trained our computer, we can give it the information for a new student, like [12, 6, 9], and it will give us a list of numbers that represent the chance of the student getting each possible grade. We can look at the list and see which grade has the highest chance, and that will be our prediction for the student's grade.


The softmax function is defined mathematically as follows:

Given an input vector z = [z1, z2, ..., zn], the softmax function computes the output vector y = [y1, y2, ..., yn] where:

yi = e^zi / (e^z1 + e^z2 + ... + e^zn)

In [12]:
import numpy as np

def softmax(x):
  if x.ndim != 1:
    print('Please provide a vector!')
  else:
    exp_x = np.exp(x)
    softmax_x = exp_x / np.sum(exp_x, keepdims=True)
    return softmax_x

ans = softmax(np.array([33.17344305,45.61961654 ,82.05405781, 80.9647098,  68.82830233, 91.52064278]))
print(ans)

[4.57181033e-26 1.16249922e-20 7.73872594e-05 2.60358426e-05
 1.39571531e-10 9.99896577e-01]


exp_x = np.exp(x), calculates the exponential of each number in the x array. This means that each number in x is raised to the power of a special number called "e". The result is a new numpy array called exp_x that has the same shape as x.

The second line, softmax_x = exp_x / np.sum(exp_x, keepdims=True), calculates the softmax function for each number in x. First, it calculates the sum of all the exponential values in the exp_x array using np.sum(exp_x, keepdims=True). The keepdims=True argument is used to make sure that the sum is a numpy array with the same shape as exp_x, which is important for the next step.

Next, it divides each value in the exp_x array by the sum that was calculated in the previous step. This gives us a new numpy array called softmax_x that contains the chance of each number in x belonging to a certain category.

### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]] 
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [13]:
#Coder here

import numpy as np

def vstack(*args):
  #print(args)
  for arg in args:
      if not isinstance(arg, np.ndarray):
          raise ValueError("Input is not a numpy array")
  return np.vstack(args)



a = np.array([[1, 2, 3], [4, 5, 6],[32,41,56]])
b = np.array([[7, 8, 9], [10, 11, 12]])
c = np.array([[13, 14, 15], [16, 17, 18]])

result = vstack(a, b, c)
print(result)

[[ 1  2  3]
 [ 4  5  6]
 [32 41 56]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [14]:
#Code here
from datetime import datetime, timedelta

def date_array(date1,date2):
  if not isinstance(date1,str) and not isinstance(date2,str):
    raise ValueError('Dates are not string type')

  try:
    dt1 = datetime.strptime(date1,'%Y-%m-%d')
    dt2 = datetime.strptime(date2,'%Y-%m-%d')
  except ValueError:
    raise ValueError('Date inputs are not given according to the asked format.')
  
  if dt1.year != dt2.year:
    raise ValueError('The year of the dates must be same')

  num_of_days = (dt2-dt1).days+1
  date_arr = np.array([dt1 + timedelta(days=i) for i in range(num_of_days)], dtype='datetime64[D]')
  return date_arr



ans = date_array('2020-11-25','2020-11-30')
print(ans)

['2020-11-25' '2020-11-26' '2020-11-27' '2020-11-28' '2020-11-29'
 '2020-11-30']


###`Q-14:` Subtract the mean of each row from a matrix.

In [15]:
#code here
import numpy as np

mat = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
x=3
y=3

# calculating the row means
row_means = np.mean(mat, axis=1)
z=0
# subtract the row means using a for loop
for i in range(x):
  
  for j in range(y):
    mat[i][j] = mat[i][j] - row_means[z]
  z+=1
  
mat

array([[-1,  0,  1],
       [-1,  0,  1],
       [-1,  0,  1]])

###`Q-15:` Swap column-1 of array with column-2 in the array.

In [16]:
import numpy as np

# create a sample 2D array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# swap column-1 with column-2
arr[:, 1], arr[:, 2] = arr[:, 2], arr[:, 1].copy()

print(arr)

[[1 3 2]
 [4 6 5]
 [7 9 8]]


In [17]:
#Code here

arr = np.arange(12).reshape(3,4)

x = arr[:,1]
y=x
print(x)
print(arr)
arr[:,1] = arr[:,2]
print(x)
print(y)
print(arr)
arr[:,2] = y

print(arr)


[1 5 9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 2  6 10]
[ 2  6 10]
[[ 0  2  2  3]
 [ 4  6  6  7]
 [ 8 10 10 11]]
[[ 0  2  2  3]
 [ 4  6  6  7]
 [ 8 10 10 11]]


###`Q-16:` Replace odd elements in arrays with -1.

In [18]:
#Code here

import numpy as np

mat = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# replace odd elements with -1
mat[mat % 2 == 1] = -1

print(mat)

[[-1  2 -1]
 [ 4 -1  6]
 [-1  8 -1]]


###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
``` 

In [19]:
#Code here

In [20]:
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

c = np.maximum(a,b)
c

array([6, 3, 1, 7, 8])

###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


Normalization in statistics is a technique used to transform data so that it has a standard scale or range. The goal of normalization is to bring all the variables in a dataset to a similar scale, making it easier to compare them.

There are several ways to normalize data, but one common approach is to rescale the data so that it has a mean of 0 and a standard deviation of 1. This is known as standardization or z-score normalization.
you know how we measure things like height, weight, and temperature, right? And sometimes, we want to compare different measurements, but they might not be in the same units or scale.

For example, one person might measure their height in inches, and another might measure in centimeters. It can be hard to compare their heights if we're using different units, right?

That's where normalization statistics come in! Basically, it's a way to make different measurements easier to compare by putting them on the same scale.

It's like if we're playing a game and we want to know who's doing better. If we just look at the score, we might think that one person is winning. But if we know how many turns each person has had, we can divide their score by the number of turns to get their average score per turn. Then, we can compare their scores more fairly!

Normalization statistics work kind of like that. They help us compare measurements by adjusting them based on things like the average, minimum, and maximum values. This makes it easier to see patterns or differences between different sets of data, even if they started out in different units or scales.

In [21]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[7370, 1480,  644, 2779, 4025],
       [1358, 1865, 2370, 2353, 8408],
       [7730, 8590, 7614, 4560, 3901],
       [2745, 1370, 7665, 6608, 7420],
       [7204, 3263, 2560, 6649, 7610],
       [6338, 3927,  830, 4006, 6805],
       [ 999, 4628, 9731, 2071, 1185],
       [1757, 6857, 6743, 2621, 4359]])

In [27]:
#Code here

arr1[:,::2]

array([[7370,  644, 4025],
       [1358, 2370, 8408],
       [7730, 7614, 3901],
       [2745, 7665, 7420],
       [7204, 2560, 7610],
       [6338,  830, 6805],
       [ 999, 9731, 1185],
       [1757, 6743, 4359]])

In [32]:
min_value = np.min(arr1)
min

644

In [33]:
max_value = np.max(arr1)
max_value

9731

In [34]:
normalized_arr = (arr1 - min_value) / (max_value - min_value)
normalized_arr

array([[0.74017828, 0.09199956, 0.        , 0.23495103, 0.37206999],
       [0.07857379, 0.13436778, 0.18994167, 0.18807087, 0.8544074 ],
       [0.77979531, 0.87443601, 0.76702982, 0.43094531, 0.35842412],
       [0.23120942, 0.07989435, 0.77264224, 0.65632222, 0.74568064],
       [0.72191042, 0.28821393, 0.21085067, 0.66083416, 0.76658963],
       [0.62660944, 0.36128535, 0.0204688 , 0.36997909, 0.67800154],
       [0.0390668 , 0.43842852, 1.        , 0.15703753, 0.0595356 ],
       [0.12248267, 0.683724  , 0.67117861, 0.21756355, 0.4088258 ]])

###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

**np.partition** is a numpy function that is used to partition a numpy array along a specified axis. The function returns a new array where the elements on one side of the partition are smaller or equal to the elements on the other side, but the elements on each side may not be in any particular order.

In [59]:
#Code here

def nthLargest(arr,n):
 nth = np.partition(arr,-n)[::-1][n-1]
 print(nth)


arr = np.array([12,34,47,7,1,0,45,41,64,13])

nthLargest(arr,4)


41


In the code np.partition(arr, -n), the negative sign before the n indicates that we want to partition the array based on the nth largest element rather than the nth smallest element.
The np.partition function can partition an array based on either the nth smallest or nth largest element. If kth is a positive integer, the array will be partitioned based on the nth smallest element, i.e., the first kth elements will be the smallest elements in the array, and the remaining elements will be the remaining elements in any order.

However, if kth is a negative integer, the array will be partitioned based on the nth largest element, i.e., the last abs(kth) elements will be the largest elements in the array, and the remaining elements will be the remaining elements in any order.

###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [67]:
#code here
a = np.array([1,2,3])
repeated_arr = np.repeat(a,3)
print(repeated_arr)

tiled_arr = np.tile(a,3)
print(tiled_arr)
new_arr = np.concatenate((repeated_arr,tiled_arr))

[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]


array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

np.repeat() takes an array and repeats each element a specified number of times, resulting in a new flattened array. For example, if we have an array [1, 2, 3] and we want to repeat each element twice, we can use np.repeat([1, 2, 3], 2) to get [1, 1, 2, 2, 3, 3]. We can also specify an array of repeat counts to apply to each element of the input array, resulting in a new flattened array with the specified number of repetitions for each element.



Sure! Here's another way to explain np.tile() without using a coding example:

np.tile() is a function in NumPy that is used to repeat an array along one or more axes. When we use np.tile(), we pass in an input array and a tuple that specifies the number of times we want to repeat the input array along each axis.

For example, suppose we have a 2D input array with shape (2, 3):
input_array = [[1, 2, 3],
               [4, 5, 6]]

If we want to repeat this array twice along the row axis and three times along the column axis, we can use the following code:
output_array = np.tile(input_array, (2, 3))
The resulting output_array will have shape (4, 9) and will look like this:
output_array = [[1, 2, 3, 1, 2, 3, 1, 2, 3],
                [4, 5, 6, 4, 5, 6, 4, 5, 6],
                [1, 2, 3, 1, 2, 3, 1, 2, 3],
                [4, 5, 6, 4, 5, 6, 4, 5, 6]]

