**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [23]:
import numpy as np

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [24]:
#Code here
arr = np.zeros(10, dtype = int)

arr[4] = 1

arr

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [25]:
#Code here

a = int(input('Give input for row numbers: '))
b = int(input('Give input for column numbers: '))


arr = np.random.randint(low=0,high=100,size=a*b).reshape((a,b))

avg = np.mean(arr)

print('array: ',arr)
print('avg: ',avg)

Give input for row numbers: 4
Give input for column numbers: 5
array:  [[91 65 96 89 56]
 [75 68 72 45 55]
 [50 63 27 48 57]
 [51 33 13 12 11]]
avg:  53.85



###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```

[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [26]:
#Code here
def onezero(a,b):
  if a>2 and b>2:
    arr = np.ones((a,b),dtype=int)
    arr[1:a-1,1:b-1] = 0
    return arr
  else: 
    return np.ones((a,b),dtype=int)


ans = onezero(2,2)
print(ans)

[[1 1]
 [1 1]]


###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [27]:
#Code here

np.linspace(0,1,12)[1:11]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [28]:
#Code here


###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [29]:
#Code here
np.linspace(0,4,25, dtype = int).reshape(5,5)

array([[0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1],
       [1, 1, 2, 2, 2],
       [2, 2, 2, 3, 3],
       [3, 3, 3, 3, 4]])

###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3]) 
```


In [30]:
#code here
import math
point = np.array([2,3]) 
distance = []
arr = np.random.randint(low=1,high=100,size=10*2).reshape((10,2))

for i in range(len(arr)):
  #print(arr[i])
  x1 = point[0]
  y1 = point[1]
  x2 = arr[i][0]
  y2 = arr[i][1]

  d = ((x2-x1)**2 + (y2-y1)**2)**.5
  #print(d)
  distance.append(d)

print(distance)

[89.37561188601732, 38.05259518088089, 43.174066289845804, 105.11898020814318, 69.46221994724903, 119.5198728245642, 107.41508273980894, 76.48529270389177, 62.16912416947821, 28.231188426986208]


###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [31]:
#Code here

import numpy as np

arr = np.zeros((6, 7, 8))

# find the indices of the 100th element
idx = np.unravel_index(99, arr.shape)

# print the indices
#print(arr)
print(idx)

(1, 5, 3)


### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [32]:
#Code here
arr = [1,2,3,4,-8,-10]

ans = np.array(arr[::-1], dtype=float)

ans


array([-10.,  -8.,   4.,   3.,   2.,   1.])

### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [33]:
#Code here

numpy_arr = np.arange(12).reshape((3,4))
print(numpy_arr.size)

12


### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01, 
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [34]:
import numpy as np

def softmax(x):
  if x.ndim != 1:
    print('Please provide a vector!')
  else:
    exp_x = np.exp(x)
    softmax_x = exp_x / np.sum(exp_x, keepdims=True)
    return softmax_x

ans = softmax(np.array([33.17344305,45.61961654 ,82.05405781, 80.9647098,  68.82830233, 91.52064278]))
print(ans)

[4.57181033e-26 1.16249922e-20 7.73872594e-05 2.60358426e-05
 1.39571531e-10 9.99896577e-01]


### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]] 
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [35]:
#Coder here

import numpy as np

def vstack(*args):
  #print(args)
  for arg in args:
      if not isinstance(arg, np.ndarray):
          raise ValueError("Input is not a numpy array")
  return np.vstack(args)



a = np.array([[1, 2, 3], [4, 5, 6],[32,41,56]])
b = np.array([[7, 8, 9], [10, 11, 12]])
c = np.array([[13, 14, 15], [16, 17, 18]])

result = vstack(a, b, c)
print(result)

[[ 1  2  3]
 [ 4  5  6]
 [32 41 56]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [51]:
#Code here
from datetime import datetime, timedelta

def date_array(date1,date2):
  if not isinstance(date1,str) and not isinstance(date2,str):
    raise ValueError('Dates are not string type')

  try:
    dt1 = datetime.strptime(date1,'%Y-%m-%d')
    dt2 = datetime.strptime(date2,'%Y-%m-%d')
  except ValueError:
    raise ValueError('Date inputs are not given according to the asked format.')
  
  if dt1.year != dt2.year:
    raise ValueError('The year of the dates must be same')

  num_of_days = (dt2-dt1).days+1
  date_arr = np.array([dt1 + timedelta(days=i) for i in range(num_of_days)], dtype='datetime64[D]')
  return date_arr



ans = date_array('2020-11-25','2020-11-30')
print(ans)

['2020-11-25' '2020-11-26' '2020-11-27' '2020-11-28' '2020-11-29'
 '2020-11-30']


###`Q-14:` Subtract the mean of each row from a matrix.

In [57]:
#code here
import numpy as np

mat = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
x=3
y=3

# calculating the row means
row_means = np.mean(mat, axis=1)
z=0
# subtract the row means using a for loop
for i in range(x):
  
  for j in range(y):
    mat[i][j] = mat[i][j] - row_means[z]
  z+=1
  
mat

array([[-1,  0,  1],
       [-1,  0,  1],
       [-1,  0,  1]])

###`Q-15:` Swap column-1 of array with column-2 in the array.

In [73]:
import numpy as np

# create a sample 2D array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# swap column-1 with column-2
arr[:, 1], arr[:, 2] = arr[:, 2], arr[:, 1].copy()

print(arr)

[[1 3 2]
 [4 6 5]
 [7 9 8]]


In [76]:
#Code here

arr = np.arange(12).reshape(3,4)

x = arr[:,1]
y=x
print(x)
print(arr)
arr[:,1] = arr[:,2]
print(x)
print(y)
print(arr)
arr[:,2] = y

print(arr)


[1 5 9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 2  6 10]
[ 2  6 10]
[[ 0  2  2  3]
 [ 4  6  6  7]
 [ 8 10 10 11]]
[[ 0  2  2  3]
 [ 4  6  6  7]
 [ 8 10 10 11]]


###`Q-16:` Replace odd elements in arrays with -1.

In [77]:
#Code here

import numpy as np

mat = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# replace odd elements with -1
mat[mat % 2 == 1] = -1

print(mat)

[[-1  2 -1]
 [ 4 -1  6]
 [-1  8 -1]]


###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
``` 

In [40]:
#Code here

In [81]:
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

c = np.maximum(a,b)
c

array([6, 3, 1, 7, 8])

###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [41]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[1848, 9508, 3164, 2698,  632],
       [9612,  617, 5125, 8363, 8485],
       [3798, 8790, 2037, 2142, 8145],
       [8116, 1656, 1291, 7371, 5279],
       [2910, 1051, 6324, 4857, 7722],
       [9647, 6041,  441, 4582, 8318],
       [2567, 4072, 6543, 9742, 9423],
       [9202,  297, 5587, 9084, 5900]])

In [42]:
#Code here

###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [43]:
#Code here

###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [44]:
#code here