# Numpy Array functions

In [1]:
import numpy as np

In [2]:
a1 = np.random.random((3,4)) 
a1 = np.round(a1*10)
a1

array([[6., 1., 8., 8.],
       [6., 8., 8., 9.],
       [6., 9., 9., 6.]])

#### max/min/sum/prod functions

In [3]:
# find max from whole matrix
np.max(a1)

9.0

In [4]:
# find max from every column
np.max(a1,axis=0)  # 0 -> column

array([6., 9., 9., 9.])

In [5]:
# find max from every row
np.max(a1,axis = 1)   # 1 -> row

array([8., 9., 9.])

In [6]:
np.min(a1)

1.0

In [7]:
# find min from every column
np.min(a1,axis=0)  # 0 -> column

array([6., 1., 8., 6.])

In [8]:
# find max from every row
np.min(a1,axis = 1)   # 1 -> row

array([1., 6., 6.])

In [9]:
np.sum(a1)

84.0

In [10]:
# find sum from all columns individually
np.sum(a1,axis=0)

array([18., 18., 25., 23.])

In [11]:
# find sum from all rows individually
np.sum(a1,axis=1)

array([23., 31., 30.])

In [12]:
np.prod(a1)

3869835264.0

In [13]:
# find product from all columns individually
np.prod(a1,axis=0)

array([216.,  72., 576., 432.])

In [14]:
# find product from all rows individually
np.prod(a1,axis=1)

array([ 384., 3456., 2916.])

#### mean/median/std/var

In [15]:
np.mean(a1)

7.0

In [16]:
np.mean(a1,axis=0)

array([6.        , 6.        , 8.33333333, 7.66666667])

In [17]:
np.mean(a1,axis=1)

array([5.75, 7.75, 7.5 ])

In [18]:
np.median(a1)

8.0

In [19]:
np.median(a1,axis=0)

array([6., 8., 8., 8.])

In [20]:
np.median(a1,axis=1)

array([7. , 8. , 7.5])

In [21]:
np.std(a1)

2.160246899469287

In [22]:
np.std(a1,axis=0)

array([0.        , 3.55902608, 0.47140452, 1.24721913])

In [23]:
np.std(a1,axis=1)

array([2.86138079, 1.08972474, 1.5       ])

In [24]:
np.var(a1)

4.666666666666667

In [25]:
np.var(a1,axis=0)

array([ 0.        , 12.66666667,  0.22222222,  1.55555556])

In [26]:
np.var(a1,axis=1)

array([8.1875, 1.1875, 2.25  ])

#### dot product

In [27]:
b1 = np.arange(12).reshape((3,4))
b1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [28]:
c1 = np.arange(11,23).reshape((4,3))
c1


array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19],
       [20, 21, 22]])

In [29]:
np.dot(b1,c1)

array([[108, 114, 120],
       [356, 378, 400],
       [604, 642, 680]])

#### round/ceil/floor

In [30]:
np.round(np.random.random((3,4))*100).astype(int)

array([[76, 93,  5, 54],
       [68, 76,  4, 68],
       [46, 43, 94, 89]])

### Indexing and Slicing

In [31]:
a1 = np.arange(10)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
a2 = np.arange(12).reshape(3,4)
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [34]:
a3 = np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [71]:
# find 6 in the matrix
a2[1,2]

6

In [72]:
# find 7 in tensor


a3[1,1,1]

7

In [73]:
# find 5,6,7 from matrix

a2[1,1:]

array([5, 6, 7])

In [52]:
# find 2,6,10 from matrix
a2[:,2]

array([ 2,  6, 10])

In [53]:
# find 5,6,9,19 from matrix

a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [56]:
#find 0,3,8,11 from matrix

a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [63]:
# find 1,3,9,11 from matrix

a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [67]:
# find 4,7 from matrix

a2[1,::3]

array([4, 7])

In [70]:
# FIND 1,2,3,5,6,7 from matrix

a2[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [76]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [78]:
# extract the middle 2d matrix

a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [80]:
# find the first and last 2d matrix

a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [83]:
# find the first matrix 2nd row

a3[0,1,:]

array([3, 4, 5])

In [84]:
# find the second matrix 2nd column

a3[1,:,1]

array([10, 13, 16])

In [85]:
# find 22,23,25,26

a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [86]:
#find 0,2,18,20

a3[0::2,0,0::2]

array([[ 0,  2],
       [18, 20]])

## Looping

In [87]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [89]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [91]:
for i in np.nditer(a2):
    print(i,end=' ')

0 1 2 3 4 5 6 7 8 9 10 11 

In [94]:
for i in np.nditer(a3):
    print(i,end=' ')

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 

## Reshaping

#### Transpose (convert rows into columns and columns into rows)

In [100]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [101]:
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

#### Ravel (converting n dimensional arrays to 1D array)

In [102]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [103]:
np.ravel(a3)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

## Stacking

#### vstack

vstack is used to stack arrays vertically (i.e., along the row axis) to create a new array. It takes a sequence of arrays as input and returns a new array that has the same number of columns as the input arrays, but with the rows stacked on top of each other.

In [104]:
a4 = np.arange(12).reshape(3,4)
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [107]:
a5 = np.arange(24,36).reshape(3,4)
a5

array([[24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35]])

In [109]:
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35]])

#### hstack

hstack, on the other hand, is used to stack arrays horizontally (i.e., along the column axis) to create a new array. It takes a sequence of arrays as input and returns a new array that has the same number of rows as the input arrays, but with the columns stacked next to each other.

In [111]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [112]:
a5

array([[24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35]])

In [113]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 24, 25, 26, 27],
       [ 4,  5,  6,  7, 28, 29, 30, 31],
       [ 8,  9, 10, 11, 32, 33, 34, 35]])

## Splitting

#### vsplit (It has to be always equal split of rows)

In [115]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [120]:
np.vsplit(a4,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

#### hsplit (It has to be always equal split of columns)

In [127]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]